export const WINDOW_ID_FLOATING_TOOLBAR = '浮动工具栏'
export const WINDOW_ID_FLOATING_TOOLBAR_HANDLE = 'floating-toolbar-handle'
export const WINDOW_TITLE_FLOATING_TOOLBAR = '浮动工具栏'
export const BACKEND_URL = 'http://127.0.0.1:3131'
export { TOOLBAR_STATE_KEY, UI_STATE_APP_WINDOW_ID, APPEARANCE_UI_STATE_KEY, APPEARANCE_KV_KEY } from '../../status'
